### ISSUE TITLE
Load by reference

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/cgp-data-store#20]
**Purpose:** sometimes we want to provide access to these data files and index the metadata that is in other peoples' buckets rather than keep copies for ourselves. 

**Concern:** the links will break. 

**Objective:** API's to make the interface seamless between the "real" files and the "stub" load by reference files.

**Comment by mikebaumann** [comment]
There is an existing issue in the HumanCellAtlas/data-store repo that represents this issue:
https://github.com/HumanCellAtlas/data-store/issues/912

The existing issue could be elaborated.
